---
application:
  name: "patchface"
  project: "aqoaif"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "patchdb"
  version: "11"
routers:
- name: "main-patchface"
  routes:
  - application_name: "patchface"
    paths:
    - "/*"
